sudo: false
language: java
jdk:
- oraclejdk8
install:
- ./gradlew --version
script:
- ./gradlew --continue build
after_success:
- git status
- echo $REPOSITORY_USERNAME
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
- if [ master == $TRAVIS_BRANCH -a $TRAVIS_PULL_REQUEST == false -a  ${REPOSITORY_USERNAME:=X} != X ]; then ./gradlew release; fi
cache:
  directories:
  - "$HOME/.gradle"
dd:
  secure: hLr9fmoS31580iFLdPDIbbbTsmg4i8VFTueQtorlwX4JEs0ALGQNB3tYkbfBjJS0ErDMLyQ0bmsjQBMa3R+EV/dCKJP8G7UTjicD3BKUTCSIQEZkfeaXVMB6XwA0Qbr+x7ATD5fptLnCPbf3UxagBI4p4RKwhiF4OGgkzx9vB7k=
