sudo: false
language: java
jdk:
- oraclejdk8
install:
- "./gradlew --version"
script:
- "./gradlew --continue --info build"
- branch=$(basename $(git symbolic-ref HEAD))
- echo $OSGI_NEXUS_SETTING
- echo $branch
- if [ "master" == $branch -a -n $OSGI_NEXUS_SETTING ]; then ./gradlew --info --continue
  release; fi
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
    secure: Hy5Diaf51yfsuLnrNiaa993AshiE++VwUZkwvj+vl+uDmnynyMZ6t1ryUgpnkOSTcwDaTtkfae97Ujd5ZE9d8EHHTDlQ0ntCb80z38ucdIfqc/cqdH9VW9qRkxRojwKvG9yf/QSC1YfNIVUnaNRsIOk40hcfQ2qhWNRr6Yy7EFU=
