sudo: false
language: java
jdk:
- oraclejdk8
install:
- "./gradlew --version"
script:
- "./gradlew --continue build"
- echo $OSGI_NEXUS_SETTING
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
- if [ "master" == $TRAVIS_BRANCH -a $TRAVIS_PULL_REQUEST == false -a -n $OSGI_NEXUS_SETTING
  ]; then ./gradlew --info --continue release; fi
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
    secure: TQaySV8DdG33e6LZ5loIVNK2WRZ2iClztFSRgw/NTEg9KA69GQMnpBXCcme/lsOlVPUkUtucR7P3QTWUAX9iJTw6Dfyew+dKu6wchBhto9/TsFG6xV43fpr5ePp2ToUNbm2+hKBXpxT4fWRvMDRJPKLgQBYsH0DAYM4IXqI5QFU=
