sudo: false

language: java

jdk:
  - oraclejdk8

install:
  - ./gradlew --version

script:
  - ./gradlew --continue build release

after_success:
  - git status

cache:
  directories:
    - $HOME/.gradle
