sudo: false
language: java
jdk:
- oraclejdk8
install:
- ./gradlew --version
script:
- ./gradlew --continue build
after_success:
- git status
- echo $REPOSITORY_USERNAME
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
- if [ master == $TRAVIS_BRANCH -a $TRAVIS_PULL_REQUEST == false -a  ${REPOSITORY_USERNAME:=X} != X ]; then ./gradlew release; fi
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: j9YcUfaC3DCdFeSM5Lo63uaM7OPBRbBmZgrV9nv2FjYprar7qmhCOOWYSOiK3KIy0+IfDhCEpenR04ENJOiVLXlv4L6VXtLWp8zzR8P74k6XlCN3sOUa4XhIwV3rY3uqTH8xjDFwbTVJodNf2RZfUYs3YlIriET9VvLpjYErOOk=
  - secure: TgyTyOAXFbmgDZ0LeXp02eK7b9w3v3LtUBl1UU0yADrQHaxX8TAamEHy9GoJ2jCt+crRFdXmISIQuA/dTan4APBtOOokZsmTYYXB41lw8GumVkiIuKXJIUtgqTo/78RmUuOnP3thTx1x57U8KTIyelnNQZDdz48tfyRbmahA0LM=
