version: '{build}'

clone_depth: 50

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))
  - ps: .\appveyor-maven-proxy.ps1
  - mvnw.cmd --version

build_script:
  - mvn verify

on_success:
  - git status
