version: '{build}'

clone_depth: 50

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - gradlew.bat --version

build_script:
  - gradlew.bat --continue build

on_success:
  - git status

cache:
  - C:\Users\appveyor\.gradle -> .gradle-wrapper\gradle-wrapper.properties
